In [14]:
#data encoding>> converting categorical columns into numeric
#Nominal/OHE
#label and ordinal encoding
#Target guided ordinal encoding

In [15]:
#Nominal/OHE >> binary vector for each categories
#example : single, married, separated
#single :[1, 0, 0]
#married: [0, 1, 0]
#separated: [0, 0, 1]

In [16]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [17]:
df = pd.DataFrame({'status': ['single', 'married', 'separated', 'single', 'single', 'married', 'married']})

In [18]:
df

status
0     single
1    married
2  separated
3     single
4     single
5    married
6    married

In [19]:
encoder = OneHotEncoder()

In [20]:
encoder

OneHotEncoder()

In [21]:
encoded = encoder.fit_transform(df[['status']]).toarray()
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [22]:
encoder.get_feature_names_out()

array(['status_married', 'status_separated', 'status_single'],
      dtype=object)

In [23]:
encoder_df = pd.DataFrame(encoded, columns = encoder.get_feature_names_out())

In [24]:
encoder_df

status_married  status_separated  status_single
0             0.0               0.0            1.0
1             1.0               0.0            0.0
2             0.0               1.0            0.0
3             0.0               0.0            1.0
4             0.0               0.0            1.0
5             1.0               0.0            0.0
6             1.0               0.0            0.0

In [25]:
#new data
encoder.transform([['single']]).toarray()

C:\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1.]])

In [28]:
pd.concat([df,encoder_df], axis=1)

status  status_married  status_separated  status_single
0     single             0.0               0.0            1.0
1    married             1.0               0.0            0.0
2  separated             0.0               1.0            0.0
3     single             0.0               0.0            1.0
4     single             0.0               0.0            1.0
5    married             1.0               0.0            0.0
6    married             1.0               0.0            0.0

In [30]:
#label encoding >> assigens unique label to the categories

In [31]:
df

status
0     single
1    married
2  separated
3     single
4     single
5    married
6    married

In [32]:
from sklearn.preprocessing import LabelEncoder


In [33]:
label_encoder = LabelEncoder()

In [34]:
label_encoder.fit_transform(df[['status']])

C:\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 2, 2, 0, 0])

In [35]:
label_encoder.transform([['single']])

C:\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([2])

In [37]:
label_encoder.transform([['separated']])

C:\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([1])

In [38]:
#ordinal encoding
#High school : 1
#graduation : 2
#pg : 3
#phd : 4


In [40]:
from sklearn.preprocessing import OrdinalEncoder

In [60]:
df = pd.DataFrame({"qualification":["HS","GR","PG","Phd","HS","HS","Phd","PG"]})

In [61]:
df

qualification
0            HS
1            GR
2            PG
3           Phd
4            HS
5            HS
6           Phd
7            PG

In [62]:
encoder=OrdinalEncoder(categories=[["HS","GR","PG","Phd"]])

In [63]:
encoder.fit_transform(df[['qualification']])

array([[0.],
       [1.],
       [2.],
       [3.],
       [0.],
       [0.],
       [3.],
       [2.]])

In [65]:
#new data
encoder.transform([['PG']])

C:\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[2.]])

In [66]:
#Target guided ordinal encoding
#relationship with with target variable
#A lot of unique categories
# Replace the categories with the mean and median of respective group target

In [68]:
df = pd.DataFrame({'time':['lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner'],
             'total_bill': [120, 130, 90, 125, 150, 190, 160, 180, 189]})

In [69]:
df

time  total_bill
0      lunch         120
1  breakfast         130
2     dinner          90
3      lunch         125
4  breakfast         150
5     dinner         190
6      lunch         160
7  breakfast         180
8     dinner         189

In [71]:
mean_price=df.groupby('time')['total_bill'].mean().to_dict()

In [72]:
mean_price

{'breakfast': 153.33333333333334, 'dinner': 156.33333333333334, 'lunch': 135.0}

In [73]:
df['time_encoded'] = df['time'].map(mean_price)

In [74]:
df

time  total_bill  time_encoded
0      lunch         120    135.000000
1  breakfast         130    153.333333
2     dinner          90    156.333333
3      lunch         125    135.000000
4  breakfast         150    153.333333
5     dinner         190    156.333333
6      lunch         160    135.000000
7  breakfast         180    153.333333
8     dinner         189    156.333333